export const AI_BOT_URL = 'https://openai.weixin.qq.com/openapi/aibot'
export const TOKENIZE_URL = 'https://openai.weixin.qq.com/openapi/nlp/tokenize'
export const NER_URL = 'https://openai.weixin.qq.com/openapi/nlp/ner'
export const SENTIMENT_URL = 'https://openai.weixin.qq.com/openapi/nlp/sentiment'
export const SENSITIVE_URL = 'https://openai.weixin.qq.com/openapi/nlp/sensitive'
